### PR TITLE
Create hacs.json

### PR DESCRIPTION
**Pull request by royto**
Add hacs.json file

Your repository can be added as custom plugin using HACS but you need to **create release** when a new code is pushed to make it visible through HACS. Only release are visible in HACS if at least one exist.

After accepting this PR, if you want your plugin available in default repositories, you need to create a PR on this project: https://github.com/hacs/default. Just need to add your repo info in this [file](https://github.com/hacs/default/blob/master/plugin)

Use this guide for this: https://hacs.xyz/docs/publish/include

Thanks in advance

### CODE REVIEW

**Comment by cbulock** [comment]
@royto Thanks for this!  I haven't used HACS yet (though it seems I should be).  I need to get that setup and test this in it, then will get an MR open for that!

**Comment by royto** [comment]
HACS is great to install and manage plugins ... 😉

**Comment by cbulock** [comment]
I ended up selling my house and moving early last summer, since then I've been so disconnected from the HASS ecosystem.  There has been so much progress made since then! Trying to get all caught back up with a new setup from scratch :)

**Comment by TheLastProject** [comment]
Just want to say: Welcome back to the Home Assistant crowd. Hope your move went well and thank you for your lovelace addon :)

**Pull request merged**
