### PR TITLE
fix compatibility with 0.106.x

### PR DESCRIPTION
**Pull request by liri**

### CODE REVIEW

**Comment by teddythanh** [comment]
It didn't work for me. The problem is still persisted.

**Comment by tiberius25** [comment]
This fix is not working

**Comment by tiberius25** [comment]
Important note: the file battery-entity.js must be in the "community" folder. It worked for me

**Comment by borland502** [comment]
Worked like a charm.  I simply cloned the patch branch of liri's and subbed out the location of the original.  Just like the sensor card, apparently one needs to make a deep copy of the config now.

**Pull request merged**
